services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: armadillo
      POSTGRES_PASSWORD: armadillo
      POSTGRES_DB: armadillo
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -lc "pnpm --filter @armadillo/api exec prisma db push --accept-data-loss && pnpm --filter @armadillo/api dev"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgres://armadillo:armadillo@postgres:5432/armadillo
    depends_on:
      - redis
      - postgres
    ports:
      - "4000:4000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pnpm --filter @armadillo/worker dev
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORKER_CONCURRENCY: 4
      DATABASE_URL: postgres://armadillo:armadillo@postgres:5432/armadillo
    depends_on:
      - redis
      - postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pnpm --filter @armadillo/web dev --hostname 0.0.0.0 --port 3000
    environment:
      API_BASE_URL: http://api:4000
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  pg_data:
